import { useEffect, useState } from 'react';
import { useAuth } from '../hooks/useAuth';
import { getCustomerBookings } from '../services/bookings';
import { getCustomerMessages } from '../services/messages';
import { getCustomerRequests } from '../services/requests';
import { getCustomerEmails } from '../services/emails';
import './pages.css';
type Item={id:string;type:string;title:string;detail:string;time:string;status:string};
export function History(){const{user}=useAuth();const[items,setItems]=useState<Item[]>([]);const[loading,setLoading]=useState(true);useEffect(()=>{if(!user)return;Promise.all([getCustomerBookings(user.id),getCustomerMessages(user.id),getCustomerRequests(user.id),getCustomerEmails(user.id)]).then(([b,m,r,e])=>{setItems([...((b.data??[]).map(x=>({id:`b-${x.id}`,type:'Booking',title:x.service?.name??'Service booking',detail:new Date(x.date).toLocaleString(),time:x.created_at,status:String(x.status)}))),...((m.data??[]).map(x=>({id:`m-${x.id}`,type:'Message',title:x.subject,detail:x.body,time:x.sent_at,status:String(x.status)}))),...((r.data??[]).map(x=>({id:`r-${x.id}`,type:'Request',title:x.request_type,detail:x.description,time:x.created_at,status:String(x.status)}))),...((e.data??[]).map(x=>({id:`e-${x.id}`,type:'Email',title:x.subject,detail:x.body,time:x.sent_at,status:String(x.status)})))] .sort((a,b)=>new Date(b.time).getTime()-new Date(a.time).getTime()));setLoading(false)})},[user]);return <div className="page"><p className="eyebrow">MY ACCOUNT</p><h1>Activity history</h1><p className="page-subtitle">Your bookings, messages, requests, and emails in one place.</p>{loading?<div className="page-loading">Loading your history…</div>:<div className="history-timeline">{items.map(item=><article key={item.id}><span>{item.type}</span><div><b>{item.title}</b><p>{item.detail}</p><small>{new Date(item.time).toLocaleString()}</small></div><em>{item.status}</em></article>)}{items.length===0&&<p className="page-empty">Your activity will appear here.</p>}</div>}</div>}
