// @ts-nocheck
import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../hooks/useAuth';
import { getActivePromotions } from '../services/promotions';
import { getActiveServices } from '../services/services';
import { getCustomerBookings } from '../services/bookings';
import { getCustomer } from '../services/customers';
import { useRealtimeTable } from '../hooks/useRealtimeTable';
import { SharedPostFeed } from '../components/SharedPostFeed';
import type { Promotion, Service, Booking, Customer } from '../types';
import { formatZMW } from '../utils/currency';
import './pages.css';

type Detail={kind:'Promotion'|'Booking';title:string;body:string;meta:string};

export function Home(){
  const {user}=useAuth(); const navigate=useNavigate();
  const [promotions,setPromotions]=useState<Promotion[]>([]); const [services,setServices]=useState<Service[]>([]); const [bookings,setBookings]=useState<Booking[]>([]); const [customer,setCustomer]=useState<Customer|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [refresh,setRefresh]=useState(0); const [selected,setSelected]=useState<Detail|null>(null);
  useEffect(()=>{if(!user)return;async function load(){setLoading(true);const[p,s,b,c]=await Promise.all([getActivePromotions(),getActiveServices(),getCustomerBookings(user.id),getCustomer(user.id)]);if(p.error||s.error||b.error)setError('Failed to load some data. Please refresh.');setPromotions((p.data??[]).slice(0,3));setServices(s.data??[]);setCustomer(c.data??null);setBookings((b.data??[]).filter(item=>new Date(item.date)>=new Date()&&!['completed','cancelled'].includes(String(item.status).toLowerCase())).slice(0,3));setLoading(false)}void load()},[user,refresh]);
  useRealtimeTable('bookings',()=>setRefresh(value=>value+1),user?`customer_id=eq.${user.id}`:undefined); useRealtimeTable('services',()=>setRefresh(value=>value+1)); useRealtimeTable('promotions',()=>setRefresh(value=>value+1));
  return <div className="page"><h1>Welcome{customer?.name?`, ${customer.name}`:''}!</h1><p className="page-subtitle">Here's what's new at Alessandro Enterprises.</p>{loading&&<div className="page-loading">Loading your dashboard...</div>}{error&&<div className="page-error">{error}</div>}{!loading&&<><section><h2>Latest Promotions</h2>{promotions.length?promotions.map(item=><button className="card detail-card" key={item.id} onClick={()=>setSelected({kind:'Promotion',title:item.title,body:item.description||'No additional details have been added.',meta:`${item.discount}% off`})}><h3>{item.title}</h3><p>{item.description}</p><span className="badge">{item.discount}% off</span><small className="view-detail">View details</small></button>):<p className="page-empty">No active promotions right now.</p>}</section><SharedPostFeed/><section><h2>Services</h2>{services.length?services.map(item=><button className="card detail-card" key={item.id} onClick={()=>navigate(`/products/${item.id}`)}><h3>{item.name}</h3><p>{item.description}</p><p className="card-meta">{item.duration?`${item.duration} min · `:''}{formatZMW(item.price)}</p><small className="view-detail">View full service and gallery</small></button>):<p className="page-empty">No services available yet.</p>}</section><section><h2>Upcoming Bookings</h2>{bookings.length?bookings.map(item=><button className="card detail-card" key={item.id} onClick={()=>setSelected({kind:'Booking',title:item.service?.name||'Service booking',body:item.notes||'No additional notes were supplied.',meta:`${new Date(item.date).toLocaleString()} · ${item.status}`})}><h3>{item.service?.name||'Service'}</h3><p className="card-meta">{new Date(item.date).toLocaleString()}</p><span className="badge">{item.status}</span><small className="view-detail">View details</small></button>):<p className="page-empty">You have no pending or upcoming bookings.</p>}</section><section><h2>Quick Links</h2><div className="quick-links"><a href="/book">Book a service</a><a href="/products">Browse products</a><a href="/updates">Latest updates</a><a href="/promotions">View promotions</a><a href="/messages">Send a message</a></div></section></>}{selected&&<div className="detail-backdrop" onMouseDown={()=>setSelected(null)}><section className="detail-modal" onMouseDown={event=>event.stopPropagation()}><button className="detail-close" onClick={()=>setSelected(null)}>×</button><p className="eyebrow">{selected.kind}</p><h2>{selected.title}</h2><p>{selected.body}</p><p className="detail-meta">{selected.meta}</p></section></div>}</div>;
}
